# Generated by Django 2.0.5 on 2018-07-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_time', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('train_accu', models.DecimalField(decimal_places=2, max_digits=4)),
                ('test_accu', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pend_time', models.DateTimeField(auto_now=True, verbose_name='pending on')),
                ('pend_outcome_time', models.DateTimeField(auto_now=True, verbose_name='checked on')),
            ],
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
